export default {
    SELECT_ANY_TEMPLATE: "Please select a campaign",
    LINK_COPIED: "Link copied",
    PLEASE_SELECT_A_CAMPAIGN: "Please select a campaign",
    REQUEST_SUBMITTED: "Your request has been successfully submitted",
    UPLOAD_CSV: "Please upload your file in .csv format",
    PROVIDE_VALID_URL: "Please provide a valid URL",
    GENERATING_VIDEO: "Generating video!",
    GENERAL_EXCEPTION_RESPONSE: "Something went wrong, please try again",
    CSV_CANNOT_BE_BLANK: "CSV cannot be blank",
    ADD_CSV_FILE: "Please add a CSV file",
    UPLOAD_BLANK_CELLS: "Your CSV has blank cells, you may want to take another look",
    MISSING_VALUE: "Missing value for this variable",
    SELECT_ONE_OPTION: "Please select at least one option",
    FILE_TOO_LARGE: "Files should not be larger than 100 MB",
    ONLY_MP4: "We only support .mp4 files",
    RESET_PASSWORD_MESSAGE: "Check your email, we've sent you a link to reset your password",
    ENTER_EMAIL: "Please enter your email",
    ENTER_VALID_EMAIL: "Please enter a valid email",
    ENTER_PASSWORD: "Please enter your password",
    ENTER_VALID_EMAIL2: "Please enter a valid email address",
    SIGNUP_VIA_GOOGLE: "Your signup method is through Google, please login using Google",
    VIDEOS_ACTIVE: "Congrats! Your videos are now active on {{link}}",
    NO_FILE_SELECTED: "No file selected",
    ENTER_VALID_URL: "Please enter a valid URL",
    PREVIEW_FAILED: "Preview failed",
    LOAD_BACKGROUND_VIDEO: "Couldn't load background video",
    NETWORK_ERROR: "Network Error",
    NOT_FOUND_404: "404 | Not Found",
    INTERNAL_SERVER_ERROR_500: "500 | Internal Server Error",
    ENTER_VALID_BACKGROUND_URL: "Please enter a valid background video URL",
    VALID_HTTP_URL: "Please enter a URL with HTTP or HTTPS",
    PREVIEW_FAILED_TRY_AGAIN: "Preview failed, please try again",
    ENTER_FIRST_NAME: "Please enter your first name",
    ENTER_LAST_NAME: "Please enter last name",
    PASSWORD_TOO_SHORT: "Password must be at least 6 characters",
    PASSWORDS_DONT_MATCH: "Your passwords do not match",
    VALID_DOMAIN_NAME: "Please provide a valid domain name",
    DOMAIN_NAME_TOO_LONG: "Domain and subdomain length must be less than 30 characters",
    VALID_SUBDOMAIN: "Please provide a valid subdomain",
    VALIDATING_DNS: "We are validating your DNS configuration, this could take up to 15 mins. You will be notified shortly. Please do not refresh this page.",
    CHECK_CNAME: "Please check your CNAME records configuration for {{domain}}. Copy and paste the above mentioned details in your DNS configuration and then validate again",
    DOMAIN_CONFIGURED_SUCCESSFULLY: "Your domain has been configured successfully. Click here to use this domain for all your videos in {{campaign_name}}"
}

